python -m main.py --target-update 2000 \
               --T-max 200000 \
               --evaluation-interval 1000 \
               --learn-start 1600 \
               --memory-capacity 1000000 \
               --replay-frequency 1 \
               --multi-step 20 \
               --architecture data-efficient \
               --hidden-size 256 \
               --learning-rate 0.0001 \
               --multi-step 1 \
               --history-length 1 \
               --env $1 \
               --wandb test_rainbow \
